/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.puppylpg.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("xyz.puppylpg.app.App")
}

tasks.register("welcome"){
    doLast {
        println("Welcome to Gradle")
    }
}

tasks.register("hello") {
    println("Hello!")
}

tasks.register("world") {
    println("world")
    dependsOn("hello")
}

