/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.puppylpg.utilities;

import xyz.puppylpg.list.LinkedList;

class JoinUtils {
    public static String join(LinkedList source) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < source.size(); ++i) {
            if (!result.isEmpty()) {
                result.append(" ");
            }
            result.append(source.get(i));
        }

        return result.toString();
    }
}
